# Generated by Django 3.1.8 on 2021-06-11 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professor',
            options={'verbose_name': 'Professor', 'verbose_name_plural': 'Professors'},
        ),
        migrations.AddField(
            model_name='professor',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.department'),
        ),
        migrations.AddField(
            model_name='professor',
            name='department_head',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='professor',
            name='time_in',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='time_out',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
