# Generated by Django 3.1.8 on 2021-06-11 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210611_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='middle_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
