# Generated by Django 3.1.8 on 2021-06-12 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_professor_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='time_in',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='time_out',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
