# Generated by Django 3.1.8 on 2021-06-13 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210612_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='time_in',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='time_out',
            field=models.DateTimeField(null=True),
        ),
    ]
