# Generated by Django 3.1.8 on 2021-06-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyloadmodel',
            name='semester',
            field=models.CharField(choices=[('first_sem', 'First sem'), ('second_sem', 'Second Sem')], default='first_sem', max_length=20),
        ),
        migrations.AddField(
            model_name='facultyloadmodel',
            name='year',
            field=models.IntegerField(default=2020),
        ),
    ]
