# Generated by Django 3.1.8 on 2021-06-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyload', '0003_auto_20210609_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyloadmodel',
            name='semester',
            field=models.CharField(choices=[('first', 'First sem'), ('second', 'Second Sem')], default='first', max_length=20),
        ),
    ]
