# Generated by Django 3.1.8 on 2021-06-12 17:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facultyload', '0008_auto_20210611_1706'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='facultyloadmodel',
            unique_together={('professor', 'schedule', 'year', 'semester', 'approved')},
        ),
    ]
