# Generated by Django 3.1.8 on 2021-06-12 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facultyload', '0009_auto_20210612_1727'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='facultyloadmodel',
            unique_together=set(),
        ),
    ]
