# Generated by Django 3.1.8 on 2021-06-13 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='lab',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='lec',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='units',
        ),
        migrations.AddField(
            model_name='subject',
            name='lab',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='lec',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='units',
            field=models.IntegerField(default=0),
        ),
    ]
