# Generated by Django 3.1.8 on 2021-06-08 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultyloading',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='facultyloadmodel',
            name='professor',
        ),
        migrations.RemoveField(
            model_name='facultyloadmodel',
            name='schedule',
        ),
        migrations.DeleteModel(
            name='FacultyLoad',
        ),
        migrations.DeleteModel(
            name='FacultyLoading',
        ),
        migrations.DeleteModel(
            name='FacultyLoadModel',
        ),
    ]
