# Generated by Django 3.1.8 on 2021-06-13 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20210613_1035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='deparment',
            new_name='department',
        ),
    ]
