# Generated by Django 3.1.8 on 2021-06-13 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20210612_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='non_stem',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='section',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='course.course'),
        ),
    ]
