# Generated by Django 3.1.8 on 2021-05-15 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_college_department'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='code',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='professor_name',
        ),
        migrations.AddField(
            model_name='professor',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.department'),
        ),
        migrations.AddField(
            model_name='professor',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='middle_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
