# Generated by Django 3.1.8 on 2021-05-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210515_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
