# Generated by Django 3.1.8 on 2021-05-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210515_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='ending_time',
            field=models.TimeField(help_text='At least 7:00 A.M.', null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='start_time',
            field=models.TimeField(help_text='At least 7:00 A.M.', null=True),
        ),
    ]
