# Generated by Django 3.1.8 on 2021-05-16 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210515_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='time_in',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='time_out',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='middle_name',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
