# Generated by Django 3.1.8 on 2021-05-01 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_section_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='main',
            new_name='_main',
        ),
    ]
