# Generated by Django 3.1.8 on 2021-05-16 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210516_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='middle_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
