# Generated by Django 3.1.8 on 2021-05-01 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210501_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='year_level',
            field=models.CharField(choices=[('first-year', '1st Year'), ('second-year', 'Second Year'), ('third-year', '3rd Year')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('part-timer', 'Part Timer')], default='regular', max_length=250),
        ),
    ]
