# Generated by Django 3.1.8 on 2021-05-01 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210501_0256'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLoadingFaculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Professors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200, null=True)),
                ('professor_name', models.CharField(max_length=200, null=True)),
                ('college', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professors',
            },
        ),
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, null=True)),
                ('year_level', models.CharField(choices=[('first-year', '1st Year'), ('second-year', 'Second Year'), ('third-year', '3rd Year')], default='first-year', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=10)),
                ('description', models.TextField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.AddField(
            model_name='adminloadingfaculty',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.professors'),
        ),
    ]
