# Generated by Django 3.1.8 on 2021-05-16 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20210516_0615'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='code',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
