# Generated by Django 3.1.8 on 2021-05-01 11:25

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20210501_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminloadingfaculty',
            name='subject',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.StructBlock([('_main', wagtail.core.blocks.BooleanBlock(default=False)), ('description', wagtail.core.blocks.TextBlock(max_length=250)), ('lec', wagtail.core.blocks.IntegerBlock(default=0)), ('lab', wagtail.core.blocks.IntegerBlock(default=0)), ('units', wagtail.core.blocks.IntegerBlock(default=0)), ('section', wagtail.core.blocks.TextBlock(max_length=250)), ('schedule', wagtail.core.blocks.TextBlock(max_length=250)), ('_type', wagtail.core.blocks.ChoiceBlock(choices=[('regular', 'Regular'), ('part-timer', 'Part Timer')], max_length=250))]))], null=True),
        ),
    ]
