# Generated by Django 3.1.8 on 2021-05-01 11:51

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_adminloadingfaculty_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminloadingfaculty',
            options={'verbose_name': 'Faculty Loading', 'verbose_name_plural': 'Faculty Loading'},
        ),
        migrations.AlterField(
            model_name='adminloadingfaculty',
            name='subject',
            field=wagtail.core.fields.StreamField([('Subject', wagtail.core.blocks.StructBlock([('_main', wagtail.core.blocks.BooleanBlock(default=False)), ('description', wagtail.core.blocks.TextBlock(max_length=250)), ('subject_type', wagtail.core.blocks.ChoiceBlock(choices=[('lecture', 'Lecture'), ('laboratory', 'Laboratory')], max_length=250)), ('units', wagtail.core.blocks.IntegerBlock(default=0)), ('section', wagtail.core.blocks.TextBlock(max_length=250)), ('schedule', wagtail.core.blocks.TextBlock(max_length=250)), ('_type', wagtail.core.blocks.ChoiceBlock(choices=[('regular', 'Regular'), ('part-timer', 'Part Timer')], max_length=250))]))], null=True),
        ),
    ]
