# Generated by Django 3.1.8 on 2021-05-16 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20210516_0624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='user',
        ),
    ]
